import * as fs from 'fs';

import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import * as ExcelJS from 'exceljs';

import { PrismaService } from '../../prisma/prisma.service';
import { BusinessReportsService, ReportResult } from './business-reports.service';
import { ReportKind, ExportQueryDto } from './dto/export-query.dto';

const KIND_TITLE: Record<ReportKind, string> = {
  [ReportKind.Revenue]: 'Revenue Report',
  [ReportKind.Expenses]: 'Expense Report',
  [ReportKind.Profit]: 'Profit & Loss Report',
};

export interface ExportFile {
  buffer: Buffer;
  filename: string;
  contentType: string;
}

@Injectable()
export class BusinessExportService {
  constructor(
    private readonly reports: BusinessReportsService,
    private readonly prisma: PrismaService,
  ) {}

  private async workspaceName(workspaceId: bigint): Promise<string> {
    const ws = await this.prisma.workspace.findUnique({
      where: { id: workspaceId },
      select: { name: true },
    });
    return ws?.name ?? 'Workspace';
  }

  // satang (string) → บาท (number)
  private baht(satang: string): number {
    return Number(satang) / 100;
  }

  private money(satang: string): string {
    return this.baht(satang).toLocaleString('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
  }

  // ── PDF ────────────────────────────────────────────────────
  async pdf(workspaceId: bigint, query: ExportQueryDto): Promise<ExportFile> {
    const [report, name] = await Promise.all([
      this.reports.build(workspaceId, query.report, query),
      this.workspaceName(workspaceId),
    ]);
    const buffer = await this.renderPdf(report, name);
    return {
      buffer,
      filename: `${query.report}-${report.period.label}.pdf`,
      contentType: 'application/pdf',
    };
  }

  /** ลงทะเบียนฟอนต์ไทยถ้ามี (PDF_FONT_PATH) — ไม่งั้น fallback Helvetica (หัวข้ออังกฤษอ่านได้, ชื่อหมวดไทยต้องมีฟอนต์) */
  private applyFont(doc: PDFKit.PDFDocument): void {
    const fontPath = process.env.PDF_FONT_PATH;
    try {
      if (fontPath && fs.existsSync(fontPath)) {
        doc.registerFont('body', fontPath);
        doc.font('body');
      }
    } catch {
      /* fallback Helvetica */
    }
  }

  private renderPdf(
    report: ReportResult,
    workspaceName: string,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.applyFont(doc);
      const s = report.summary;

      // Header
      doc.fontSize(18).text(KIND_TITLE[report.kind], { align: 'left' });
      doc.moveDown(0.2);
      doc.fontSize(10).fillColor('#555').text(workspaceName);
      doc
        .fontSize(10)
        .fillColor('#555')
        .text(
          `Period: ${report.period.start} to ${report.period.end} (${report.period.label})`,
        );
      doc.moveDown(0.8);
      doc.fillColor('#000');

      // Summary
      doc.fontSize(13).text('Summary');
      doc.moveDown(0.3);
      const summaryRows: [string, string][] = [
        ['Revenue (THB)', this.money(s.revenue)],
        ['Expenses (THB)', this.money(s.expense)],
        ['Net Profit (THB)', this.money(s.net)],
        ['Margin', s.margin == null ? '-' : `${s.margin}%`],
        ['Transactions', String(s.count)],
        [
          'Revenue Growth',
          s.revenueGrowthPct == null ? '-' : `${s.revenueGrowthPct}%`,
        ],
        [
          'Expense Growth',
          s.expenseGrowthPct == null ? '-' : `${s.expenseGrowthPct}%`,
        ],
      ];
      doc.fontSize(10);
      for (const [k, v] of summaryRows) {
        doc.text(`${k}: ${v}`);
      }
      doc.moveDown(0.8);

      // Categories
      doc.fontSize(13).text(
        report.kind === ReportKind.Revenue
          ? 'Revenue by Category'
          : 'Expenses by Category',
      );
      doc.moveDown(0.3);
      doc.fontSize(10);
      if (report.categories.length === 0) {
        doc.fillColor('#888').text('No data').fillColor('#000');
      } else {
        for (const c of report.categories) {
          doc.text(`${c.name}  —  ${this.money(c.total)} (${c.pct}%)`);
        }
      }
      doc.moveDown(0.8);

      // Trend
      doc.fontSize(13).text('Trend');
      doc.moveDown(0.3);
      doc.fontSize(9);
      for (const b of report.trend) {
        doc.text(
          `${b.label}   Revenue ${this.money(b.income)}   Expense ${this.money(
            b.expense,
          )}   Net ${this.money(b.net)}`,
        );
      }

      doc.moveDown(1);
      doc
        .fontSize(8)
        .fillColor('#999')
        .text(`Generated by Smart Finance · ${KIND_TITLE[report.kind]}`, {
          align: 'center',
        });

      doc.end();
    });
  }

  // ── Excel ──────────────────────────────────────────────────
  async excel(workspaceId: bigint, query: ExportQueryDto): Promise<ExportFile> {
    const [report, workspaceName] = await Promise.all([
      this.reports.build(workspaceId, query.report, query),
      this.workspaceName(workspaceId),
    ]);
    const wb = new ExcelJS.Workbook();
    wb.creator = 'Smart Finance';
    wb.created = new Date();

    // Summary sheet
    const sum = wb.addWorksheet('Summary');
    sum.columns = [
      { header: 'Metric', key: 'metric', width: 24 },
      { header: 'Value', key: 'value', width: 20 },
    ];
    const s = report.summary;
    sum.addRow({ metric: 'Workspace', value: workspaceName });
    sum.addRow({ metric: 'Report', value: KIND_TITLE[report.kind] });
    sum.addRow({
      metric: 'Period',
      value: `${report.period.start} → ${report.period.end}`,
    });
    sum.addRow({ metric: 'Revenue (THB)', value: this.baht(s.revenue) });
    sum.addRow({ metric: 'Expenses (THB)', value: this.baht(s.expense) });
    sum.addRow({ metric: 'Net Profit (THB)', value: this.baht(s.net) });
    sum.addRow({ metric: 'Margin (%)', value: s.margin ?? '-' });
    sum.addRow({ metric: 'Transactions', value: s.count });
    sum.addRow({ metric: 'Revenue Growth (%)', value: s.revenueGrowthPct ?? '-' });
    sum.addRow({ metric: 'Expense Growth (%)', value: s.expenseGrowthPct ?? '-' });
    sum.getRow(1).font = { bold: true };

    // Categories sheet
    const cat = wb.addWorksheet('Categories');
    cat.columns = [
      { header: 'Category', key: 'name', width: 28 },
      { header: 'Amount (THB)', key: 'amount', width: 18 },
      { header: 'Share (%)', key: 'pct', width: 12 },
    ];
    cat.getRow(1).font = { bold: true };
    for (const c of report.categories) {
      cat.addRow({ name: c.name, amount: this.baht(c.total), pct: c.pct });
    }

    // Trend sheet
    const trend = wb.addWorksheet('Trend');
    trend.columns = [
      { header: 'Period', key: 'label', width: 16 },
      { header: 'Revenue (THB)', key: 'income', width: 16 },
      { header: 'Expense (THB)', key: 'expense', width: 16 },
      { header: 'Net (THB)', key: 'net', width: 16 },
    ];
    trend.getRow(1).font = { bold: true };
    for (const b of report.trend) {
      trend.addRow({
        label: b.label,
        income: this.baht(b.income),
        expense: this.baht(b.expense),
        net: this.baht(b.net),
      });
    }

    const buffer = Buffer.from(await wb.xlsx.writeBuffer());
    return {
      buffer,
      filename: `${query.report}-${report.period.label}.xlsx`,
      contentType:
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    };
  }
}
